apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-downloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-downloader
  template:
    metadata:
      labels:
        app: yt-downloader
    spec:
      containers:
        - name: downloader
          image: yt-downloader:latest
          ports:
            - containerPort: 4545
